version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.6.3
    resource_class: medium

parameters:
  deploy_infra:
    type: boolean
    default: false
  deploy_app:
    type: boolean
    default: false
  destroy_infra:
    type: boolean
    default: false
  verify_app:
    type: boolean
    default: false
  delete_pods:
    type: boolean
    default: false

commands:
  aws-authentication:
    steps:
      - run:
          name: Authenticate with AWS OIDC
          command: |
            apk add --no-cache curl jq aws-cli
            echo "${CIRCLE_OIDC_TOKEN}" > /tmp/token.jwt || true
            export AWS_ROLE_ARN="arn:aws:iam::183631319967:role/sagar-oidc"
            export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/token.jwt"

            aws sts assume-role-with-web-identity \
                  --role-arn "$AWS_ROLE_ARN" \
                  --role-session-name "CircleCIJob" \
                  --web-identity-token "$(cat $AWS_WEB_IDENTITY_TOKEN_FILE)" \
                  --duration-seconds 3600 > /tmp/aws-credentials.json

            AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' /tmp/aws-credentials.json)
            AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' /tmp/aws-credentials.json)
            AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' /tmp/aws-credentials.json)

            if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_SESSION_TOKEN" ]; then
              echo "ERROR: AWS credentials not retrieved properly"
              exit 1
            fi

            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $BASH_ENV
            echo "export AWS_REGION=ap-south-1" >> $BASH_ENV
            echo "export AWS_DEFAULT_REGION=ap-south-1" >> $BASH_ENV
            source $BASH_ENV

            aws sts get-caller-identity

  aws-authentication-docker:
    steps:
      - run:
          name: Authenticate with AWS OIDC
          command: |
            sudo apt-get update && sudo apt-get install -y curl jq less

            echo "${CIRCLE_OIDC_TOKEN}" > /tmp/token.jwt || true
            export AWS_ROLE_ARN="arn:aws:iam::183631319967:role/sagar-oidc"
            export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/token.jwt"
            
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install --update
            export PATH=/usr/local/bin:$PATH
            aws --version

            aws sts assume-role-with-web-identity \
                  --role-arn "$AWS_ROLE_ARN" \
                  --role-session-name "CircleCIJob" \
                  --web-identity-token "$(cat $AWS_WEB_IDENTITY_TOKEN_FILE)" \
                  --duration-seconds 3600 > /tmp/aws-credentials.json
            
            AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' /tmp/aws-credentials.json)
            AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' /tmp/aws-credentials.json)
            AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' /tmp/aws-credentials.json)

            if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_SESSION_TOKEN" ]; then
              echo "ERROR: AWS credentials not retrieved properly"
              exit 1
            fi
            
            echo "export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $BASH_ENV
            echo "export AWS_REGION=ap-south-1" >> $BASH_ENV
            echo "export AWS_DEFAULT_REGION=ap-south-1" >> $BASH_ENV
            
            export AWS_PAGER=""
            echo 'export AWS_PAGER=""' >> $BASH_ENV
            source $BASH_ENV

            aws sts get-caller-identity

  install-kubectl:
    steps:
        - run:
            name: Authenticate with AWS OIDC
            command: |
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              sudo chmod +x kubectl
              sudo mv kubectl /usr/local/bin/
              kubectl version --client

  update-eks-kube-config:
    steps:
        - run:
            name: EKS config
            command: |
              source $BASH_ENV
              aws eks update-kubeconfig --name hello-world-cluster --region ap-south-1 --alias eks-cluster

  verify-eks:
    steps:
        - run:
            name: Kubernetes verification
            command: |
              kubectl config current-context
              echo "========================="
              echo "====kubectl get nodes===="
              echo "========================="
              kubectl get nodes
              echo "==================================="
              echo "====aws sts get-caller-identity===="
              echo "==================================="
              aws sts get-caller-identity
              echo "============================================================="
              echo "====kubectl get configmap -n kube-system aws-auth -o yaml===="
              echo "============================================================="
              kubectl get configmap -n kube-system aws-auth -o yaml
              echo "=============================="
              echo "====kubectl get namespaces===="
              echo "=============================="
              kubectl get namespaces
              echo "========================================================================"
              echo "====aws eks list-fargate-profiles --cluster-name hello-world-cluster===="
              echo "========================================================================"
              aws eks list-fargate-profiles --cluster-name hello-world-cluster
              echo "====================================================================================================================="
              echo "====aws eks describe-fargate-profile --cluster-name hello-world-cluster --fargate-profile-name hello-world-fargate===="
              echo "====================================================================================================================="
              aws eks describe-fargate-profile --cluster-name hello-world-cluster --fargate-profile-name hello-world-fargate
              echo "=================================="
              echo "====kubectl get deployments -A===="
              echo "=================================="
              kubectl get deployments -A
              echo "==========================="
              echo "====kubectl get pods -A===="
              echo "==========================="
              kubectl get pods -A
              echo "==============================="
              echo "====kubectl get services -A===="
              echo "==============================="
              kubectl get services -A
              echo "================================"
              echo "====kubectl describe pods -A===="
              echo "================================"
              kubectl describe pods -A
              echo "==============================================="
              echo "====kubectl describe ingress my-app-ingress===="
              echo "==============================================="
              kubectl describe ingress my-app-ingress
              echo "==========================================================="
              echo "====aws eks describe-cluster --name hello-world-cluster===="
              echo "==========================================================="
              aws eks describe-cluster --name hello-world-cluster
              echo "=========================="
              echo "====kubectl get svc -A===="
              echo "=========================="
              kubectl get svc -A

  common:
    steps:
      - checkout
      - aws-authentication-docker
      - install-kubectl
      - update-eks-kube-config

  delete-pods:
    steps:
      - run:
          name: Delete all the pods in hello-world namespace to recreate new ones
          command: |
            kubectl delete pod -n hello-world --all
    #         kubectl rollout restart deployment hello-world -n hello-world

  # recreate-deployment:
    # steps:
    #   - run:
    #       name: Restart deployment hello-world
    #       command: |
    #         kubectl rollout restart deployment hello-world -n hello-world

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "Hello, World!"

  terraform-plan:
    executor: terraform-executor
    working_directory: ~/terraform
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-authentication
      - run:
          name: Terraform Init
          command: |
            source $BASH_ENV
            cd terraform && terraform init -backend-config=backend/dev
      - run:
          name: Terraform Plan
          command: |
            source $BASH_ENV
            cd terraform && terraform plan
            
  terraform-apply:
    executor: terraform-executor
    working_directory: ~/terraform
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-authentication
      - run:
          name: Terraform Init
          command: |
            source $BASH_ENV
            cd terraform && terraform init -backend-config=backend/dev
      - run:
          name: Terraform Apply
          command: |
            source $BASH_ENV
            cd terraform && terraform apply -auto-approve

  terraform-destroy:
    executor: terraform-executor
    steps:
      - checkout
      - aws-authentication
      - run:
          name: Terraform Init
          command: |
            source $BASH_ENV
            cd terraform && terraform init -backend-config=backend/dev
      - run:
          name: Terraform Destroy
          command: |
            source $BASH_ENV
            cd terraform && terraform destroy -auto-approve   

  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - setup_remote_docker
      - aws-authentication-docker
      - run:
          name: Authenticate with AWS ECR
          command: |
            source $BASH_ENV
            aws ecr get-login-password --region ap-south-1 | \
            docker login --username AWS --password-stdin 183631319967.dkr.ecr.ap-south-1.amazonaws.com
      - run:
          name: Build & Push Docker Image
          command: |
            docker build -t hello-world .
            docker tag hello-world:latest 183631319967.dkr.ecr.ap-south-1.amazonaws.com/hello-world:latest
            docker push 183631319967.dkr.ecr.ap-south-1.amazonaws.com/hello-world:latest

  deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - common
      - run:
          name: Deploy to Kubernetes (Fargate)
          command: |
            kubectl apply -f k8s/namespace.yaml
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
            kubectl apply -f k8s/configmap.yaml
            kubectl apply -f k8s/ingress.yaml
            kubectl apply -f k8s/alb-controller.yaml
      - verify-eks

  verify-deployments:
    docker:
      - image: circleci/python:latest
    steps:
      - common
      - verify-eks

  delete-pods:
    docker:
      - image: circleci/python:latest
    steps:
      - common
      - delete-pods

# jobs to destroy k8s manifestations. + need to use docker file for the application

workflows:
  terraform-deploy:
    when: << pipeline.parameters.deploy_infra >>
    jobs:
      - terraform-plan
      - terraform-apply-approval:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - terraform-apply-approval
  
  build-and-deploy:
    when: << pipeline.parameters.deploy_app >>
    jobs:
      - build
      - deploy:
          requires:
            - build

  verify-deployment:
    when: << pipeline.parameters.verify_app >>
    jobs:
      - verify-deployments

  delete-pods:
    when: << pipeline.parameters.delete_pods >>
    jobs:
      - delete-pods

  terraform-destroy:
    when: << pipeline.parameters.destroy_infra >>
    jobs:
      - terraform-destroy
