apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # - rolearn: arn:aws:iam::183631319967:role/eks-fargate-pod-execution-role
    #   username: system:node:{{SessionName}}
    #   groups:
    #     - system:bootstrappers
    #     - system:nodes
    #     - system:node-proxier
    - rolearn: arn:aws:iam::183631319967:role/sagar-oidc
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::183631319967:role/temp-ec2-eks
      username: temp-ec2-eks
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::183631319967:user/devops
      username: devops
      groups:
        - system:masters
