apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: ap-south-1   # Change to your preferred AWS region
  version: "1.28"      # Change to latest EKS version if needed

vpc:
  cidr: "192.168.0.0/16"
  clusterEndpoints:
    publicAccess: true
    privateAccess: false

managedNodeGroups:
  - name: node-group-1
    instanceTypes: ["t3.medium"]
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        albIngress: true
        imageBuilder: true

  - name: node-group-2
    instanceTypes: ["t3.medium"]
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
    iam:
      withAddonPolicies:
        ebs: true
        efs: true
        albIngress: true
        imageBuilder: true

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ecr-access-sa
        namespace: default
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
